services:

  db:
    image: postgres:16
    container_name: prototype2-db
    environment:
      POSTGRES_DB: prototype2
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: #instead of pulling a pre-built image, build one
      context: ./PROTOTYPE2 #the folder in which the docker file resides.
      dockerfile: Dockerfile
    container_name: prototype2-app
    ports:
      - "8080:8080"
    environment:
      PGHOST: db # tells Spring Boot the database host is the "db" container
      PGPORT: 5432
      PGDATABASE: prototype2
      PGUSER: admin
      PGPASSWORD: password
      JWT_SECRET: thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd
      CORS_ORIGINS: http://localhost:3000 # allowed frontend origin
    depends_on:
      - db

  frontend:
    build:
      context: ./Prototype-FrontEnd-main
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE: http://localhost:8080
    container_name: prototype2-frontend
    ports:
      - "3000:3000"
    depends_on:
      - app

volumes:
  postgres-data:
